# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_users:
            entity: { class: AppBundle\Entity\User, property: email }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            guard:
                authenticators:
                    - app.security.login_form_authenticator
            # activate different ways to authenticate
            logout:
                path: /logout
            switch_user: ~
    encoders:
        AppBundle\Entity\User: bcrypt
    access_control:
#  не гибкий вариант контроля доступа, лучше в каждом контроллере или методе
#        - { path: ^/admin, roles: ROLE_USER }
    role_hierarchy:
        # для переключения между юзерами к любому урл ?_switch_user=__user_login__
        ROLE_ADMIN: [ROLE_MANAGE_GENUS, ROLE_ALLOWED_TO_SWITCH]

